name: 'Pull request backport via label'
description: 'Backport pull request based on backport label'
branding:
  icon: corner-left-down
  color: gray-dark
inputs:
  token:
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/backport.sh
      shell: bash
